- name: Install dependencies
  ansible.builtin.package:
    name:
      - gnupg
    state: present

- name: Check if MongoDB GPG key already exists
  ansible.builtin.stat:
    path: /usr/share/keyrings/mongodb-server-8.0.gpg
  register: gpg_key

- name: Download MongoDB GPG key
  ansible.builtin.get_url:
    url: https://www.mongodb.org/static/pgp/server-8.0.asc
    dest: /tmp/mongodb-server-8.0.asc
    mode: '400'
  when: not gpg_key.stat.exists

- name: Convert and store the GPG key in keyrings
  ansible.builtin.command:
    cmd: "gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor /tmp/mongodb-server-8.0.asc"
  args:
    creates: /usr/share/keyrings/mongodb-server-8.0.gpg

- name: Clean up the temporary file
  ansible.builtin.file:
    path: /tmp/mongodb-server-8.0.asc
    state: absent

- name: Add MongoDB repository to sources list
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list.d/mongodb-org-8.0.list"
    line: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse"
    create: true
    mode: '400'
    state: present

- name: Install MongoDB
  ansible.builtin.apt:
    name: mongodb-org
    update_cache: true
    state: present

- name: Start MongoDB
  ansible.builtin.service:
    name: mongod
    state: started
