---
- name: Configure OpenPath server
  hosts: openpath
  become: true
  remote_user: root
  gather_facts: false

  tasks:
    - name: Setup nginx
      ansible.builtin.include_role:
        name: nginx
      vars:
        # role_dir would resolve to nginx directory
        nginx_conf_file: "{{ playbook_dir }}/templates/nginx_conf.j2"
        nginx_domain_name: "{{ inventory_hostname }}"

    - name: Setup mongodb
      ansible.builtin.include_role:
        name: mongodb

    - name: Setup e-mission-server
      ansible.builtin.include_role:
        name: e_mission_server

    - name: Enable and configure UFW
      block:
        - name: Enable UFW
          community.general.ufw:
            state: enabled

        - name: Allow SSH
          community.general.ufw:
            rule: allow
            port: 22
