---
- name: Configure Traisi Move server
  hosts: traisimove
  become: true
  remote_user: root

  tasks:
    - name: Configure firewall
      block:
        - name: Allow loopback traffic
          ansible.builtin.iptables:
            chain: INPUT
            in_interface: lo
            jump: ACCEPT

        - name: Allow input ESTABLISHED and RELATED
          ansible.builtin.iptables:
            chain: INPUT
            ctstate:
              - ESTABLISHED
              - RELATED
            jump: ACCEPT

        - name: Allow output ESTABLISHED and RELATED
          ansible.builtin.iptables:
            chain: OUTPUT
            ctstate:
              - ESTABLISHED
              - RELATED
            jump: ACCEPT

        - name: Allow input SSH
          ansible.builtin.iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 22
            jump: ACCEPT

        - name: Allow input HTTP
          ansible.builtin.iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 80
            jump: ACCEPT

        - name: Allow input HTTPS
          ansible.builtin.iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 443
            jump: ACCEPT

        - name: Allow output HTTPS
          ansible.builtin.iptables:
            chain: OUTPUT
            protocol: tcp
            destination_port: 443
            jump: ACCEPT

        - name: Drop all other inbound traffic
          ansible.builtin.iptables:
            chain: INPUT
            jump: DROP
            in_interface: eth0
            protocol: all

    - name: Setup nginx
      ansible.builtin.include_role:
        name: nginx
      vars:
        nginx_conf_file: "{{ playbook_dir }}/templates/nginx_conf.j2"
        nginx_domain_name: "{{ inventory_hostname }}"

    - name: Setup mongodb
      ansible.builtin.include_role:
        name: mongodb

    - name: Setup e-mission-server
      ansible.builtin.include_role:
        name: e_mission_server

    - name: Setup admin dashboard
      ansible.builtin.include_role:
        name: op_admin_dashboard
