- name: Delete Miniconda
  ansible.builtin.file:
    path: "~/miniconda-23.5.2"
    state: absent

- name: Install and setup Miniconda
  ansible.builtin.shell:
    cmd: "source setup/setup_conda.sh Linux-x86_64 && source setup/setup.sh"
    chdir: ~/e-mission-server
    creates: ~/miniconda-23.5.2
  args:
    executable: /bin/bash
  environment:
    CONDA_ALWAYS_YES: true

- name: Restart e-mission-server
  ansible.builtin.service:
    name: e-mission-server
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
