- name: Download the repository
  ansible.builtin.git:
    repo: 'https://github.com/e-mission/e-mission-server'
    dest: ~/e-mission-server
    version: 869796b81b75f25fdc883c6926bfe5d37052d063
  notify:
    - Delete Miniconda # Otherwise the installation will fail
    - Install and setup Miniconda
    - Restart e-mission-server

- name: Copy start_e-mission-server.sh
  ansible.builtin.copy:
    src: files/start_e-mission-server.sh
    dest: /root/start_e-mission-server.sh
    mode: '700'
  notify:
    - Restart e-mission-server

- name: Deploy e-mission-server service
  ansible.builtin.template:
    src: "files/e-mission-server.service"
    dest: "/etc/systemd/system/e-mission-server.service"
    mode: '400'
  notify:
    - Reload systemd
    - Restart e-mission-server

- name: Setup hourly analysis
  block:
    - name: Copy start_analysis.sh
      ansible.builtin.copy:
        src: files/start_analysis.sh
        dest: /root/start_analysis.sh
        mode: '700'

    - name: Setup hourly analysis cron job
      ansible.builtin.cron:
        name: "Start hourly analysis"
        minute: "0"
        job: "/root/start_analysis.sh"

- name: Setup hourly silent ios push
  block:
    - name: Copy start_silent_ios_push.sh
      ansible.builtin.copy:
        src: files/start_silent_ios_push.sh
        dest: /root/start_silent_ios_push.sh
        mode: '700'

    - name: Setup hourly silent ios push cron job
      ansible.builtin.cron:
        name: "Start silent ios push"
        minute: "30"
        job: "/root/start_silent_ios_push.sh"
