- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable"
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: Get Docker gateway
  ansible.builtin.command: "{% raw %} docker network inspect bridge -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' {% endraw %}"
  register: docker_gateway_result
  changed_when: (docker_gateway | default(None)) != docker_gateway_result.stdout

- name: Set Docker gateway fact
  ansible.builtin.set_fact:
    docker_gateway: "{{ docker_gateway_result.stdout }}"
